### ISSUE TITLE
panic report(s) :)

### ISSUE THREAD

**Issue by dpc** [vmchale/file-sniffer#2] opened 2017-06-05 03:26 UTC
```
thread 'main' panicked at 'OS String invalid.: "./rust/rust/build/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu/zzz�"', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::result::unwrap_failed
   7: libsniff::prelude::read_all
   8: libsniff::prelude::read_all
   9: libsniff::prelude::read_all
  10: libsniff::prelude::read_all
  11: libsniff::prelude::read_all
  12: libsniff::prelude::read_all
  13: libsniff::prelude::read_all
  14: libsniff::prelude::read_all
  15: sniff::main
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by dpc** [comment] 2017-06-05 03:27
```
thread 'main' panicked at 'Error parsing .gitignore: Syntax("Error parsing regex near \'(Shar\' at character offset 0: Unclosed parenthesis.")', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::result::unwrap_failed
   7: libsniff::prelude::read_all
   8: libsniff::prelude::read_all
   9: libsniff::prelude::read_all
  10: sniff::main
  11: main
  12: __libc_start_main
  13: _start
```

**Comment by dpc** [comment] 2017-06-05 05:08
Seem to me that the `.gitignore` parsing is not ignoring comments (lines starting with `#`). Interestingly `ripgrep` fails in the same way.

**Comment by vmchale** [comment] 2017-06-05 16:31
I edited the parser and it should be fixed now. Thanks for the detailed bug report!

I can't reproduce the on my system. Is your file system using something other than unicode or ascii for paths? And are you on windows?

**Comment by dpc** [comment] 2017-06-05 17:21
The first problem is with Rust git repository. It seems Rust source code have a tests that involves paths that are not valid unicode. Unforunately Unix paths are a binary blob and are not guaranteed to be unicode.

**Comment by vmchale** [comment] 2017-06-07 02:01
Ok, made a small patch to prevent any nasty undesired panics and may update with byte-based regexes later. Thanks again for the report!

**Closed** 2017-06-07 02:01 UTC
